### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by aratnikovmxmgt** [alexchantastic/figma-export#11]
Hey there!
I know Thanksgiving is still two months away, but it's never too early to give thanks where it's due! 🎉 Just wanted to say a huge thank you for this super useful script. It’s been a lifesaver, and I'm grateful in this very day - not just in November! 🦃🍂 

Keep up the awesome work!

**Comment by alexchantastic** [comment]
❤️ Thanks! I really appreciate it!
