### ISSUE TITLE
Error 'No such team' while downloading drafts

### ISSUE THREAD

**Issue by ampil** [alexchantastic/figma-export#12]
Can you please help?

I followed your [instruction](https://github.com/alexchantastic/figma-export/wiki/Downloading-draft-files) to retrieve draft's folder id. 
I got a URL exactly as `
https://www.figma.com/api/folders/XXXXXXXXX/paginated_files?file_type=&sort_order=desc&sort_column=updated_at&page_size=50` and extracted `XXXXXXXXX`. There are 9 digits in the id.

While running `npm run get-team-files XXXXXXXXX` I got an error `No such team XXXXXXXXX`. 

Previously, when I provided project id (19 digits) it worked fine and a json file generated successfully. 

What might be the issue?

I am using `git bash` on Windows 11. `npm` version is 10.8.3, `Node.js` v20.7.0.

**Comment by alexchantastic** [comment]
Happy to help!

Since drafts are a project, you need to run `get-project-files` instead of `get-team-files`.

**Comment by ampil** [comment]
Thank you, that worked!
I updated Node.js next (thanks to this [topic](https://github.com/alexchantastic/figma-export/issues/2)), and it worked as well.

Thank you for your help!
