### ISSUE TITLE
We need windows/mac os guide for main figma users - designers, and designers dont understand code by default 😢

### ISSUE THREAD

**Issue by soatari** [alexchantastic/figma-export#7]
Please...

**Comment by alexchantastic** [comment]
Unfortunately, I built this tool out of a need I had myself and the easiest way to get it done was for it to be a CLI tool. I do plan on eventually creating more of a guided CLI wizard experience, but I don't really have the time right now to build that out.

Running this on Windows or macOS should be fairly simple though. You just need to install [node](https://nodejs.org/) and then follow the instructions in the README.

**Comment by alexchantastic** [comment]
I've written a macOS guide for beginners here: https://github.com/alexchantastic/figma-export/wiki/Complete-beginner-guide

A Windows guide is coming soon!
