### ISSUE TITLE
Not logged if you navigate after successful login

### ISSUE THREAD

**Issue by hpmiguel** [alexchantastic/figma-export#9]
After a successful login (cookies on .auth/user.json), When you goto a file url, the login banner appears

<img width="812" alt="Captura de pantalla 2024-09-02 a las 20 10 54" src="https://github.com/user-attachments/assets/d40396d8-31ba-4cbb-813c-4539f117a65c">

**Comment by alexchantastic** [comment]
I'm not sure if I get what bug you're trying to report. Can you clarify what steps are required to reproduce this?

**Comment by hpmiguel** [comment]
Sure, When I run download.spec, after login successful (cookies stored on .auth/user.json) (tested both token and creds) when test go to url file, banner login appears again and it is not possible click on menu in order to download.

My Env:
figma-export 2.0.1
OS, MacOsX 14.6.1
NodeJs 20.17.0

<img width="1279" alt="Captura de pantalla 2024-09-04 a las 19 21 23" src="https://github.com/user-attachments/assets/6c473c35-eaff-4055-a69a-49a43359218c">

**Comment by alexchantastic** [comment]
This log in modal seems to appear if you are not authenticated. If you are commenting out the line you mentioned in #8, then it's likely that you are actually not authenticating. I think solving #8 should solve this.

**Comment by hpmiguel** [comment]
I believe it is not related to the other issue. 

In this execution I ve commented the line of the other issue in order to pass the auth.setup. Then I can check user.json cookies has content, but not authn token key, and this is the problem I think. I attached to you the file without values
[user.json](https://github.com/user-attachments/files/16898542/user.json)

On which OS or browser do you test it? what kind of figma plan have you? Feel free not answer, its only for find differences.

**Comment by hpmiguel** [comment]
Sorry my fault, thank you
